import eyetrajectoriespy as et

def test_version_and_public_symbols():
    assert et.__version__=="0.46.0.dev0"
    required={
        "FunctionalMixedEffectsFullRefitBootstrapResult","bootstrap_functional_mixed_effects_full_refit","functional_mixed_effects_variance_bootstrap_frame","functional_mixed_effects_bootstrap_identity_frame","compare_functional_mixed_effects_bootstraps",
        "FunctionalMixedEffectsBootstrapResult","FunctionalMixedEffectsBandResult","bootstrap_functional_mixed_effects_coefficients","functional_mixed_effects_simultaneous_bands",
        "ConditionalTransferEntropyResult","ConditionalTransferEntropyCircularShiftTestResult","conditional_transfer_entropy","conditional_transfer_entropy_local_frame","conditional_transfer_entropy_circular_shift_test","plot_conditional_transfer_entropy_circular_shift_test","conditional_transfer_entropy_reporting_text","conditional_transfer_entropy_circular_shift_reporting_text",
        "TransferEntropySensitivityResult","transfer_entropy_parameter_sensitivity","plot_transfer_entropy_sensitivity","transfer_entropy_parameter_sensitivity_reporting_text",
        "DiscreteTransferEntropyResult","TransferEntropyCircularShiftTestResult","discrete_transfer_entropy","transfer_entropy_local_frame","transfer_entropy_circular_shift_test","plot_transfer_entropy_circular_shift_test","transfer_entropy_reporting_text","transfer_entropy_circular_shift_reporting_text",
        "MathematicalContract","get_mathematical_contract","list_mathematical_contracts","mathematical_contract_frame",
        "DelayEmbeddingResult","EmbeddingDelayDiagnosticResult","EmbeddingDimensionDiagnosticResult","RecurrenceNetworkResult","recurrence_network","recurrence_network_node_frame","recurrence_network_summary_frame","plot_recurrence_network_degree","recurrence_network_reporting_text","JointRecurrenceResult","joint_recurrence_matrix","joint_recurrence_component_frame","joint_rqa_metrics","plot_joint_recurrence","joint_recurrence_reporting_text","RecurrenceResult","RecurrenceRadiusProfileResult","RQAResult","RQAMeanBootstrapResult","RQAParameterSensitivityResult","WindowedRQAResult","WindowedRQAFunctionalResult","WindowedRQASensitivityResult","WindowedRQAMeanBandResult",
        "LocalDivergenceResult","KantzDivergenceResult","KantzParameterSensitivityResult","LargestLyapunovResult","LyapunovParameterSensitivityResult","MultivariateIAAFTResult","MultivariateSurrogateNonlinearityResult","generate_multivariate_iaaft_surrogates","multivariate_iaaft_diagnostics_frame","multivariate_surrogate_nonlinearity_test","plot_multivariate_iaaft_diagnostics","plot_multivariate_surrogate_nonlinearity","multivariate_iaaft_reporting_text","multivariate_surrogate_nonlinearity_reporting_text","SurrogateNonlinearityResult","PoincareCrossingResult","LocalReturnMapResult","ReturnMapStabilityResult",
        "delay_embed_trajectory","embedding_delay_diagnostics","embedding_dimension_diagnostics",
        "recurrence_matrix","recurrence_radius_profile","rqa_metrics","rqa_parameter_sensitivity","bootstrap_rqa_metric_means","windowed_rqa","windowed_rqa_trajectory_set","windowed_rqa_sensitivity","windowed_rqa_functional_mean_band","cross_recurrence_matrix","cross_rqa_metrics",
        "local_divergence_curve","kantz_divergence_curve","kantz_parameter_sensitivity","estimate_largest_lyapunov_rosenstein","estimate_largest_lyapunov_kantz","lyapunov_parameter_sensitivity","surrogate_nonlinearity_test",
        "poincare_crossings","fit_local_return_map","return_map_stability",
        "plot_embedding_delay_diagnostics","plot_embedding_dimension_diagnostics","plot_recurrence","plot_recurrence_rate_curve","plot_rqa_metric_mean_bootstrap","plot_rqa_sensitivity","plot_windowed_rqa","plot_windowed_rqa_trajectories","plot_windowed_rqa_sensitivity",
        "plot_kantz_sensitivity","plot_local_divergence","plot_lyapunov_sensitivity","plot_surrogate_nonlinearity","plot_poincare_return_map",
        "recurrence_radius_profile_reporting_text","rqa_metric_mean_bootstrap_reporting_text","rqa_reporting_text","rqa_parameter_sensitivity_reporting_text","windowed_rqa_reporting_text","windowed_rqa_functional_reporting_text","windowed_rqa_sensitivity_reporting_text","windowed_rqa_mean_band_reporting_text","kantz_parameter_sensitivity_reporting_text","largest_lyapunov_reporting_text","lyapunov_parameter_sensitivity_reporting_text",
        "surrogate_nonlinearity_reporting_text","return_map_stability_reporting_text",
        "TrajectorySet","TrajectoryDistanceSensitivityResult","trajectory_distance_sensitivity","trajectory_distance_comparison_frame","trajectory_distance_neighbor_frame","plot_trajectory_distance_rank_correlations","trajectory_distance_sensitivity_reporting_text","DiscreteFrechetResult","DynamicTimeWarpingResult","FunctionalMixedEffectsResult","fit_functional_mixed_effects_regression","functional_mixed_effects_coefficient_frame","functional_random_effect_frame","plot_functional_mixed_effects_coefficient","plot_functional_random_effects","functional_mixed_effects_reporting_text","FunctionOnScalarResult","FunctionOnScalarBootstrapResult","FunctionOnScalarBandResult","fit_function_on_scalar_regression","bootstrap_function_on_scalar_coefficients","function_on_scalar_simultaneous_bands","function_on_scalar_coefficient_frame","plot_function_on_scalar_coefficients","function_on_scalar_reporting_text","discrete_frechet_distance","pairwise_discrete_frechet_distances","dynamic_time_warping_distance","pairwise_dynamic_time_warping_distances","plot_dynamic_time_warping_alignment","dynamic_time_warping_reporting_text","fit_fpca","fit_mfpca","fit_multilevel_fpca","fit_compositional_fpca","FPCAScoreUncertaintyResult","FPCASpectrumUncertaintyResult",
        "register_to_landmarks","fit_elastic_fpca","simulate_planar_trajectories","heading_function","signed_curvature_function","turning_rate_function","trajectory_tortuosity",
        "fit_scalar_on_function_regression","plot_fpca_component",
        "IrregularTrajectorySet","from_irregular_long_dataframe_native","bootstrap_fpca_stability",
        "fit_phase_fpca","compare_registered_unregistered_fpca","to_skfda_basis",
        "split_conformal_fpca_anomaly","conformal_fpca_anomaly_frame","plot_conformal_fpca_anomaly","conformal_fpca_anomaly_reporting_text","diagnose_fpca_outliers","leave_one_group_out_fpca_influence",
        "ConformalFunctionalAnomalyResult","FunctionalOutlierResult","FPCAInfluenceResult","detect_functional_outliers_skfda",
        "plot_fpca_outlier_diagnostics","plot_fpca_influence",
        "FPCACrossValidationResult","FPCAComponentBandResult","FPCAComponentEnvelopeResult",
        "cross_validate_fpca_reconstruction","summarise_fpca_cross_validation",
        "select_fpca_components_cv","bootstrap_fpca_component_bands","fpca_component_band_frame","bootstrap_fpca_component_envelopes",
        "plot_fpca_cross_validation","plot_fpca_component_band","plot_fpca_component_envelope",
        "fpca_cross_validation_reporting_text","fpca_component_band_reporting_text","fpca_component_envelope_reporting_text",
        "FPCASubspaceComparisonResult","FPCASubspaceStabilityResult",
        "fpca_eigenvalue_gap_table","compare_fpca_subspaces",
        "bootstrap_fpca_subspace_stability","summarise_fpca_subspace_stability",
        "plot_fpca_subspace_stability","fpca_eigengap_reporting_text",
        "fpca_subspace_stability_reporting_text",
        "SparseFPCAResult","sparse_dimension_summary","to_fdapy_irregular",
        "fit_sparse_fpca_fdapy","sparse_fpca_score_frame",
        "sparse_fpca_reporting_text","plot_sparse_irregular_dimension",
        "FunctionalMeanBandResult","multiplier_functional_mean_band",
        "functional_mean_band_frame","plot_functional_mean_band",
        "functional_mean_band_reporting_text","bootstrap_fpca_score_uncertainty","fpca_score_uncertainty_frame","plot_fpca_score_uncertainty","fpca_score_uncertainty_reporting_text","bootstrap_fpca_spectrum_uncertainty","fpca_spectrum_uncertainty_frame","plot_fpca_spectrum_uncertainty","fpca_spectrum_uncertainty_reporting_text",
        "FPCARegressionCVResult","FPCARegressionPredictionIntervalResult","FPCARegressionSlopeBandResult","FPCARegressionUncertaintyResult","FPCAWildBootstrapProjectionResult","FPCAWildBootstrapFamilyTestResult","FPCAWildBootstrapMonteCarloDiagnosticResult","FPCAWildBootstrapSimultaneousResult","FPCAWildBootstrapTruncationScanResult","FPCAWildBootstrapTruncationSelectionResult","FPCANestedRegressionCVResult",
        "bootstrap_fpca_regression_uncertainty","wild_bootstrap_fpca_projection","scan_wild_bootstrap_fpca_truncations","select_fpca_wild_bootstrap_truncation","fpca_wild_bootstrap_truncation_scan_frame","fpca_wild_bootstrap_truncation_selection_frame","plot_fpca_wild_bootstrap_truncation_scan","fpca_wild_bootstrap_truncation_reporting_text","fpca_wild_bootstrap_projection_frame","plot_fpca_wild_bootstrap_projection","fpca_wild_bootstrap_projection_reporting_text","fpca_wild_bootstrap_projection_family_test","fpca_wild_bootstrap_family_test_frame","fpca_wild_bootstrap_family_test_monte_carlo_diagnostics","fpca_wild_bootstrap_monte_carlo_diagnostic_frame","plot_fpca_wild_bootstrap_family_test","plot_fpca_wild_bootstrap_monte_carlo_diagnostics","fpca_wild_bootstrap_family_test_reporting_text","fpca_wild_bootstrap_monte_carlo_reporting_text","fpca_wild_bootstrap_projection_simultaneous_interval","fpca_wild_bootstrap_simultaneous_frame","plot_fpca_wild_bootstrap_simultaneous_interval","fpca_wild_bootstrap_simultaneous_reporting_text","fpca_regression_future_prediction_interval","fpca_regression_future_prediction_frame","plot_fpca_regression_future_prediction_interval","fpca_regression_future_prediction_reporting_text","fpca_regression_slope_simultaneous_band","fpca_regression_slope_band_frame","plot_fpca_regression_slope_band","fpca_regression_slope_band_reporting_text","fpca_regression_slope_uncertainty_frame","fpca_regression_prediction_uncertainty_frame","plot_fpca_regression_slope_uncertainty","plot_fpca_regression_mean_prediction_uncertainty","fpca_regression_uncertainty_reporting_text","cross_validate_fpca_regression","summarise_fpca_regression_cv",
        "select_fpca_regression_components","nested_cross_validate_fpca_regression",
        "plot_fpca_regression_cv","plot_nested_fpca_regression_cv",
        "fpca_regression_cv_reporting_text","fpca_nested_regression_cv_reporting_text",
    }
    assert required <= set(et.__all__)
    for name in required:
        assert hasattr(et,name)
