"""eyetrajectoriespy: functional and continuous eye-tracking trajectory analysis."""

from .analysis import (
    cluster_fpca_scores,
    fit_scalar_on_function_regression,
    functional_l2_distance,
    nearest_trajectory_indices,
    pairwise_functional_distances,
    score_distance_matrix,
)
from .backends import detect_functional_outliers_skfda, to_skfda_basis, to_skfda_grid
from .compositional import (
    alr_transform,
    fit_compositional_fpca,
    inverse_alr,
    reconstruct_compositional_fpca,
)
from .elastic import fit_elastic_fpca
from .fpca import (
    component_trajectories,
    fit_fpca,
    fit_mfpca,
    fpca_score_frame,
    functional_trapezoid_weights,
    reconstruct_fpca,
    select_n_components,
    transform_fpca,
)
from .io import from_irregular_long_dataframe, from_long_dataframe
from .irregular import (
    common_overlap_interval,
    from_irregular_long_dataframe_native,
    irregular_sampling_summary,
    make_common_grid,
    resample_irregular_to_common_grid,
    resample_irregular_to_grid,
)
from .kinematics import (
    acceleration_magnitude_function,
    cumulative_path_length,
    differentiate_trajectories,
    distance_to_landmark_function,
    speed_function,
)
from .multilevel import fit_multilevel_fpca
from .outliers import diagnose_fpca_outliers, leave_one_group_out_fpca_influence
from .phase import (
    compare_registered_unregistered_fpca,
    fit_phase_fpca,
    phase_landmark_frame,
    phase_trajectory_set,
    registration_sensitivity_frame,
)
from .plotting import (
    plot_fpca_component,
    plot_fpca_stability,
    plot_fpca_variance,
    plot_planar_trajectories,
    plot_reconstruction_curve,
    plot_registration,
    plot_trajectory_overlay,
    plot_warping_functions,
)
from .preprocessing import (
    center_on_landmark,
    interpolate_short_gaps,
    normalize_coordinates,
    normalize_time,
    resample_to_grid,
    smooth_trajectories,
)
from .registration import phase_summary, register_to_landmarks, warping_displacement
from .reporting import (
    fpca_reporting_text,
    fpca_stability_reporting_text,
    multilevel_fpca_reporting_text,
    registration_sensitivity_reporting_text,
    summarise_fpca,
    summarise_trajectory_set,
)
from .simulate import simulate_aoi_probability_trajectories, simulate_planar_trajectories
from .stability import (
    bootstrap_fpca_stability,
    component_similarity_matrix,
    fpca_reconstruction_curve,
    match_fpca_components,
    reconstruction_error_by_curve,
    summarise_fpca_stability,
)
from .types import (
    BasisProjectionResult,
    ClusterResult,
    CompositionalFPCAResult,
    ElasticFPCAResult,
    FPCAResult,
    FPCAInfluenceResult,
    FPCAStabilityResult,
    FunctionalOutlierResult,
    FunctionalRegressionResult,
    IrregularTrajectorySet,
    MultilevelFPCAResult,
    RegistrationResult,
    RegistrationSensitivityResult,
    TrajectorySet,
)
from .validation import (
    validate_common_grid,
    validate_no_long_missing_runs,
    validate_simplex,
    validate_trajectory_set,
)

__version__ = "0.3.0.dev0"

__all__ = [
    "TrajectorySet",
    "IrregularTrajectorySet",
    "FPCAResult",
    "FPCAStabilityResult",
    "FPCAInfluenceResult",
    "RegistrationResult",
    "RegistrationSensitivityResult",
    "CompositionalFPCAResult",
    "MultilevelFPCAResult",
    "ElasticFPCAResult",
    "FunctionalRegressionResult",
    "FunctionalOutlierResult",
    "ClusterResult",
    "BasisProjectionResult",
    "from_long_dataframe",
    "from_irregular_long_dataframe",
    "from_irregular_long_dataframe_native",
    "irregular_sampling_summary",
    "common_overlap_interval",
    "make_common_grid",
    "resample_irregular_to_grid",
    "resample_irregular_to_common_grid",
    "validate_trajectory_set",
    "validate_common_grid",
    "validate_simplex",
    "validate_no_long_missing_runs",
    "resample_to_grid",
    "interpolate_short_gaps",
    "smooth_trajectories",
    "normalize_time",
    "normalize_coordinates",
    "center_on_landmark",
    "functional_trapezoid_weights",
    "fit_fpca",
    "fit_mfpca",
    "transform_fpca",
    "reconstruct_fpca",
    "component_trajectories",
    "select_n_components",
    "fpca_score_frame",
    "register_to_landmarks",
    "warping_displacement",
    "phase_summary",
    "alr_transform",
    "inverse_alr",
    "fit_compositional_fpca",
    "reconstruct_compositional_fpca",
    "fit_multilevel_fpca",
    "phase_trajectory_set",
    "fit_phase_fpca",
    "phase_landmark_frame",
    "compare_registered_unregistered_fpca",
    "registration_sensitivity_frame",
    "fit_elastic_fpca",
    "differentiate_trajectories",
    "speed_function",
    "acceleration_magnitude_function",
    "distance_to_landmark_function",
    "cumulative_path_length",
    "functional_l2_distance",
    "pairwise_functional_distances",
    "nearest_trajectory_indices",
    "score_distance_matrix",
    "cluster_fpca_scores",
    "fit_scalar_on_function_regression",
    "diagnose_fpca_outliers",
    "leave_one_group_out_fpca_influence",
    "component_similarity_matrix",
    "match_fpca_components",
    "bootstrap_fpca_stability",
    "summarise_fpca_stability",
    "reconstruction_error_by_curve",
    "fpca_reconstruction_curve",
    "simulate_planar_trajectories",
    "simulate_aoi_probability_trajectories",
    "summarise_trajectory_set",
    "summarise_fpca",
    "fpca_reporting_text",
    "fpca_stability_reporting_text",
    "registration_sensitivity_reporting_text",
    "multilevel_fpca_reporting_text",
    "plot_trajectory_overlay",
    "plot_planar_trajectories",
    "plot_fpca_variance",
    "plot_fpca_stability",
    "plot_reconstruction_curve",
    "plot_fpca_component",
    "plot_registration",
    "plot_warping_functions",
    "to_skfda_grid",
    "detect_functional_outliers_skfda",
    "to_skfda_basis",
]
